/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagingIndexRouteImport } from './routes/messaging.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as ProfilePersonIdRouteImport } from './routes/profile.$personId'
import { Route as MessagingPersonIdRouteImport } from './routes/messaging.$personId'
import { Route as JobsJobIdIndexRouteImport } from './routes/jobs.$jobId.index'
import { Route as JobsJobIdApplyRouteImport } from './routes/jobs.$jobId.apply'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagingIndexRoute = MessagingIndexRouteImport.update({
  id: '/messaging/',
  path: '/messaging/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePersonIdRoute = ProfilePersonIdRouteImport.update({
  id: '/profile/$personId',
  path: '/profile/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagingPersonIdRoute = MessagingPersonIdRouteImport.update({
  id: '/messaging/$personId',
  path: '/messaging/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdIndexRoute = JobsJobIdIndexRouteImport.update({
  id: '/jobs/$jobId/',
  path: '/jobs/$jobId/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdApplyRoute = JobsJobIdApplyRouteImport.update({
  id: '/jobs/$jobId/apply',
  path: '/jobs/$jobId/apply',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/messaging/$personId': typeof MessagingPersonIdRoute
  '/profile/$personId': typeof ProfilePersonIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/messaging/': typeof MessagingIndexRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/messaging/$personId': typeof MessagingPersonIdRoute
  '/profile/$personId': typeof ProfilePersonIdRoute
  '/jobs': typeof JobsIndexRoute
  '/messaging': typeof MessagingIndexRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/jobs/$jobId': typeof JobsJobIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/messaging/$personId': typeof MessagingPersonIdRoute
  '/profile/$personId': typeof ProfilePersonIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/messaging/': typeof MessagingIndexRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/network'
    | '/notifications'
    | '/search'
    | '/messaging/$personId'
    | '/profile/$personId'
    | '/jobs/'
    | '/messaging/'
    | '/jobs/$jobId/apply'
    | '/jobs/$jobId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/network'
    | '/notifications'
    | '/search'
    | '/messaging/$personId'
    | '/profile/$personId'
    | '/jobs'
    | '/messaging'
    | '/jobs/$jobId/apply'
    | '/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/network'
    | '/notifications'
    | '/search'
    | '/messaging/$personId'
    | '/profile/$personId'
    | '/jobs/'
    | '/messaging/'
    | '/jobs/$jobId/apply'
    | '/jobs/$jobId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NetworkRoute: typeof NetworkRoute
  NotificationsRoute: typeof NotificationsRoute
  SearchRoute: typeof SearchRoute
  MessagingPersonIdRoute: typeof MessagingPersonIdRoute
  ProfilePersonIdRoute: typeof ProfilePersonIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
  MessagingIndexRoute: typeof MessagingIndexRoute
  JobsJobIdApplyRoute: typeof JobsJobIdApplyRoute
  JobsJobIdIndexRoute: typeof JobsJobIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messaging/': {
      id: '/messaging/'
      path: '/messaging'
      fullPath: '/messaging/'
      preLoaderRoute: typeof MessagingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$personId': {
      id: '/profile/$personId'
      path: '/profile/$personId'
      fullPath: '/profile/$personId'
      preLoaderRoute: typeof ProfilePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messaging/$personId': {
      id: '/messaging/$personId'
      path: '/messaging/$personId'
      fullPath: '/messaging/$personId'
      preLoaderRoute: typeof MessagingPersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/': {
      id: '/jobs/$jobId/'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId/'
      preLoaderRoute: typeof JobsJobIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/apply': {
      id: '/jobs/$jobId/apply'
      path: '/jobs/$jobId/apply'
      fullPath: '/jobs/$jobId/apply'
      preLoaderRoute: typeof JobsJobIdApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NetworkRoute: NetworkRoute,
  NotificationsRoute: NotificationsRoute,
  SearchRoute: SearchRoute,
  MessagingPersonIdRoute: MessagingPersonIdRoute,
  ProfilePersonIdRoute: ProfilePersonIdRoute,
  JobsIndexRoute: JobsIndexRoute,
  MessagingIndexRoute: MessagingIndexRoute,
  JobsJobIdApplyRoute: JobsJobIdApplyRoute,
  JobsJobIdIndexRoute: JobsJobIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
